### ISSUE TITLE
Install fails :Cannot read property 'rateLimitsEnabled' of undefined

### ISSUE THREAD

**Issue by Debadarsini** [CartoDB/CartoDB-SQL-API#476]
Install fails with following error

/CartoDB-SQL-API/app/server.js:142
            rateLimitsEnabled: global.settings.ratelimits.rateLimitsEnabled
                                                         ^

TypeError: Cannot read property 'rateLimitsEnabled' of undefined
    at App (/CartoDB-SQL-API/app/server.js:142:58)
    at Object.<anonymous> (/CartoDB-SQL-API/app.js:94:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by dgaubert** [comment]
You will need to update your configuration file. Please check: https://github.com/CartoDB/CartoDB-SQL-API/blob/c9bc11078d900a258c7afd8ed2a90659cfc51825/config/environments/development.js.example#L111-L122
