### ISSUE TITLE
Copyfrom timeout test fails intermitently

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/CartoDB-SQL-API#611]
The test sets an arbitrary timeout of 10 ms and expects the query to be slower, but at least in my case most of the time it isn't:
```
  1) copy-endpoints
       timeout
         should fail with copyfrom and timeout:

      Uncaught AssertionError [ERR_ASSERTION]: Invalid response status code.
     Expected: 429
     Got: 200
     Body: {"time":0.004,"total_rows":6}
      + expected - actual

      -200
      +429
      
      at Server.<anonymous> (test/support/assert.js:84:28)
      at emitCloseNT (net.js:1618:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Algunenano** [comment]
Closing stale ticket
