### ISSUE TITLE
Could not fetch metadata about the affected tables: cannot connect to the database

### ISSUE THREAD

**Issue by OlivierVernin** [CartoDB/CartoDB-SQL-API#662]
How to troubleshoot the credentials used by SQL-API when having a cannot connect to the database.

For both SQL-API version 5.0.1 and 6.0.0

A table get_parcels_1592904945291 was created by importing a geojson file on the builder. Initially, the table was private but switching to a public table doesn't change anything.

When trying to access the table from the builder UI (or directly calling the SQL-API), the SQLapi returns an error every time.

> [2020-06-29 13:30:33.666] [INFO] [default] - [Mon, 29 Jun 2020 13:30:33 GMT] 185.43.214.138 GET xxx.com/user/olivier/api/v2/sql?sort_order=asc&rows_per_page=0&page=0&api_key=XXXXXXX&q=SELECT+*+FROM+(SELECT+*+FROM+olivier.get_parcels_1592904945291)+__wrapped 500 26 ms -> application/json; charset=utf-8 ({"authorization":3,"getConnectionParams":2,"init":11,"finish":4,"total":20}) ({"statusCode":500,"message":"cannot connect to the database"}) ({"request":{"sql":{"type":"query","sql":"SELECT   FROM  SELECT   FROM olivier get parcels 1592904945291    wrapped"}}})
> [2020-06-29 13:30:39.841] [ERROR] console - Error on query explain 'SELECT * FROM (SELECT * FROM olivier.get_parcels_1592904945291) __wrapped': Could not fetch metadata about the affected tables: cannot connect to the database
> [2020-06-29 13:30:39.842] [ERROR] console - EXCEPTION REPORT: Error: cannot connect to the database
>     at /home/ubuntu/CartoDB-SQL-API/node_modules/cartodb-psql/lib/psql.js:227:23
>     at BoundPool.<anonymous> (/home/ubuntu/CartoDB-SQL-API/node_modules/pg-pool/index.js:115:11)
>     at /home/ubuntu/CartoDB-SQL-API/node_modules/generic-pool/lib/generic-pool.js:339:9
>     at BoundPool.<anonymous> (/home/ubuntu/CartoDB-SQL-API/node_modules/pg-pool/index.js:99:7)
>     at Client.<anonymous> (/home/ubuntu/CartoDB-SQL-API/node_modules/pg/lib/client.js:207:5)
>     at Connection.emit (events.js:198:13)
>     at Socket.<anonymous> (/home/ubuntu/CartoDB-SQL-API/node_modules/pg/lib/connection.js:88:10)
>     at Socket.emit (events.js:198:13)
>     at emitErrorNT (internal/streams/destroy.js:91:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

Checking the db credentials stored on redis (db 5), i can see the following data fields:
- `database_publicuser` 
- `database_password`
- `database_host`
- `database_name`

Note that there is no `database_user` field.

When connecting directly with psql command, the connection to `database_name` with credentials `database_user` and `database_password` is working fine. 

I'm not sure which credentials are used by the SQL-API to connect to the database, how can i log this information?

**Comment by OlivierVernin** [comment]
found the issue, it was a wrongly configured port number in the production.js configuration file
